---
services:
  actualbudget:
    image: docker.io/actualbudget/actual-server:latest
    container_name: actual-budget
    ports:
      - 5007:5006
    volumes:
      - "${path_to_actual_budget}:/data"
    environment:
      - ACTUAL_UPLOAD_FILE_SYNC_SIZE_LIMIT_MB=20
      - ACTUAL_UPLOAD_SYNC_ENCRYPTED_FILE_SYNC_SIZE_LIMIT_MB=50
      - ACTUAL_UPLOAD_FILE_SIZE_LIMIT_MB=20
    restart: unless-stopped
