---
services:
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"  # Expose Redis port
    environment:
      - REDIS_PASSWORD=${redis_password}
    volumes:
      - "${path_to_redis_config}:/data"  # Persist Redis data
    restart: always  # Auto-restart container on failure
    command: ["redis-server", "--requirepass", "${redis_password}"]